// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.ElectronicComponent", b =>
                {
                    b.HasBaseType("Domain.Item");

                    b.Property<string>("LinkToDatasheet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MountingStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Tolerance")
                        .HasColumnType("float");

                    b.ToTable("ElectronicComponent");
                });

            modelBuilder.Entity("Domain.Capacitor", b =>
                {
                    b.HasBaseType("Domain.ElectronicComponent");

                    b.Property<double>("Capacitance")
                        .HasColumnType("float");

                    b.Property<double>("Voltage")
                        .HasColumnType("float");

                    b.ToTable("Capacitors");
                });

            modelBuilder.Entity("Domain.FerriteBead", b =>
                {
                    b.HasBaseType("Domain.ElectronicComponent");

                    b.Property<double>("Impedance")
                        .HasColumnType("float");

                    b.Property<double>("MaxDcCurrent")
                        .HasColumnType("float");

                    b.Property<double>("MaxDcResistance")
                        .HasColumnType("float");

                    b.ToTable("FerriteBeads");
                });

            modelBuilder.Entity("Domain.GenericElectronicComponent", b =>
                {
                    b.HasBaseType("Domain.ElectronicComponent");

                    b.ToTable("GenericElectronicComponents");
                });

            modelBuilder.Entity("Domain.Resistor", b =>
                {
                    b.HasBaseType("Domain.ElectronicComponent");

                    b.Property<string>("PowerRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resistance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Resistors");
                });

            modelBuilder.Entity("Domain.ElectronicComponent", b =>
                {
                    b.HasOne("Domain.Item", null)
                        .WithOne()
                        .HasForeignKey("Domain.ElectronicComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Capacitor", b =>
                {
                    b.HasOne("Domain.ElectronicComponent", null)
                        .WithOne()
                        .HasForeignKey("Domain.Capacitor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.FerriteBead", b =>
                {
                    b.HasOne("Domain.ElectronicComponent", null)
                        .WithOne()
                        .HasForeignKey("Domain.FerriteBead", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.GenericElectronicComponent", b =>
                {
                    b.HasOne("Domain.ElectronicComponent", null)
                        .WithOne()
                        .HasForeignKey("Domain.GenericElectronicComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Resistor", b =>
                {
                    b.HasOne("Domain.ElectronicComponent", null)
                        .WithOne()
                        .HasForeignKey("Domain.Resistor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
